server:
  port: 8085
  servlet:
    context-path: 
spring:
  resources:
    cache:
       period: 3600
management:
  endpoints:
    web:
      cors:
        allowed-methods:

        - GET
        allowed-headers:

        - "*"
        allowed-origins:

        - http://localhost:8080

        - http://localhost:8089
        
        - http://localhost:8093

        - http://localhost:18080

        - http://localhost:18081

        - http://localhost:18082

        - http://localhost:18083

        - http://localhost:18084

        - http://localhost:18085

        - http://localhost:18086

        - http://localhost:18087

        - http://localhost:18088

        - http://localhost:18089

        - http://20.203.7.60:8080

        - http://20.203.7.60:8089

        - http://20.203.7.60:18080

        - http://20.203.7.60:18081

        - http://20.203.7.60:18082

        - http://20.203.7.60:18083

        - http://20.203.7.60:18084

        - http://20.203.7.60:18086

        - http://20.203.7.60:18087

        - http://20.203.7.60:18088

        - http://20.203.7.60:18089
        
        - http://localhost:9999

        - http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com
        allow-credentials: false
