spring:
  config:
    location: classpath:/config/
  jackson:
    date-format: "yyyy-MM-dd"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    rest:
      basePath: /test
    elasticsearch:
      properties:
        host: localhost
        port: 9300
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/ife-infra-oauth2/user
      additionalUri: http://localhost:9999/ife-infra-oauth2/oauth/{token}/get/additionalInfo

vpms:
  server:
    port: 9130

microservices:
  gatewayServiceId: api-management

#Config SMS Gateway
smsgateway:
  resource:
    host: http://10.138.90.170:8081/aviva/sms/send
    method : POST
    enable: false

#Config Email Server
emailserver:
  resource:
    sender: SOE DXC
    username: SOEsystemDXC@gmail.com
    password: P@ssword123456
    mail.smtp.host: smtp.gmail.com
    mail.smtp.port: 587
    mail.smtp.starttls.enable: true
    mail.smtp.auth: true
    mail.debug: true
    mail.smtp.ssl.enable: false
    mail.smtp.ssl.trust: smtp.gmail.com
    mail.smtp.connectiontimeout: 5000
    mail.smtp.timeout: 5000
    mail.transport.protocol: smtp 
    template:
      quotation: C:/Users/tnguyen539/Documents/OMNI/email_template
computeRuntime : 1
#1 : vpms, = 2 : product express(PX). 
