spring:
  main:
      allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    password: P@ssword123
    timeout: 10000    
    jedis:
      pool:
        max-idle: 100 # max idle connections in the pool
        min-idle: 0 # min idle connections in the pool
        max-wait: 30000 # time limit to get a connection - only applies if maxActive is finite
  config:
    location: classpath:/config/
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    time-zone: "Asia/Saigon"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
  data:
    elasticsearch:
      properties:
        host: localhost
        port: 9300
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: false
        
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/        
                     
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/ife-infra-oauth2/user
      additionalUri: http://localhost:9999/ife-infra-oauth2/oauth/{token}/get/additionalInfo
      
vpms:
  server:
    uri: http://ec2-18-136-45-157.ap-southeast-1.compute.amazonaws.com/vpms/v1/rest/exec/9130
    fileName: document-center.vpm
    vpmsType: VN
                  
# Micro Service Group IDs      
microservices:
  gatewayServiceId: api-management
  caseServiceId: case-management
#URI Case
case:
    api:
      caseUri: /cases/life/rul
      caseByIdUri: /cases/life/rul/{ID}
#Cache expire time.
cacheManager:
  redisExpiredTime: 3600000
esign:
  pdfRepository: http://20.203.133.141:81/pdf-repository/pdf-repository/

# Configuration for multithread
executor:
  corePoolSize: 1
  maxPoolSize: 5
  queueCapacity: 50
  
template:
  user:
    default: admin 
computeRuntime : 2
#1 : vpms, = 2 : product express(PX).

calc:
  server:
    uri: http://ec2-18-139-187-180.ap-southeast-1.compute.amazonaws.com/PX_Calculator
