server:
  port: 18080
  ssl:
    enabled: false
    key-store: /home/integral/IFE-Base/config/oauth2/keystore
    key-alias: ife
    key-store-password: changeit
    key-password: changeit
  servlet:
    session:
      timeout: 9000
    context-path: /AgencySales
remote:
  server:
    url: http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com/ipos-api
    user: ''
    password: ''
    2fa:
      url: http://localhost:18080/ipos-2fa

spring:
  main:
    allow-bean-definition-overriding: true
  resources:
    cache:
      period: 3600
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html
    mode: HTML5
  servlet:
    multipart:
      enabled: true

user:
  passwordCharsContainUsername: 3
  passwordPattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[~!@#$%^&*()_+=])(?=[\S]+$).{8,}$

domain:
  name: http://localhost:18080/AgencySales/

esign:
  internal:
      uploadDocumentUrl: http://20.203.133.164:57002
      prepareDocumentUrl: http://20.203.133.164:57003
      prepareAdHocWorkstepUrl: http://20.203.133.164:57004
      redirectToWSIUrl: http://20.203.133.164:50300
      serverBaseUrl: http://20.203.133.164
      webServerUrl: http://localhost:8089
  service:
    use: kofax
documentRetrievalHandlerId: defaultDocumentRetrievalHandler
sdweb:
  document:
    load:
      mode: WEBSERVICE
  loadform:
    servlet: /esignature/loadform/
  loadservice:
    url: http://103.21.70.29/sdweb/load/doc?ref_id=
  loadservlet:
    url: http://103.21.70.29/sdweb/load/bydms
  plugins:
    dmsid: de.softpro.sdweb.plugins.impl.ExtFileDms
  preloadservice:
    url: http://103.21.70.29/sdweb/services/preload?wsdl
  repository: http://103.21.70.29/pdf-repository/
  result:
    cancel: cancel
    success: success
  signdocmobile:
    chrome:
      callbackurl: googlechrome-x-callback://x-callback-url/open/?url=
    redirect: /salecase/esignature/redirect?url=
    url:
      external: signdocmobile://x-callback-rul/openURLExternal?url=
      internal: signdocmobile://x-callback-rul/openURLInternal?url=

app:
  port:
    http: 18080
    https: 1443
  requireChannel: http

2fa_authentication:
  enable: false

onemapapi:
  country: sgp
  detail: /API/services.svc/revgeocode
  search: /API/services.svc/basicSearch
  token: qo/s2TnSUmfLz+32CvLC4RMVkzEFYjxqyti1KhByvEacEdMWBpCuSSQ+IFRT84QjGPBCuz/cBom8PfSm3GjEsGc8PkdEEOEr
  url: https://developers.onemap.sg/commonapi/search?searchVal={0}&returnGeom=Y&getAddrDetails=Y&pageNum=1
onemapapiusa:
  countryusa: USA
  detailusa: /API/services.svc/revgeocode
  searchusa: /API/services.svc/basicSearch
  tokenusa: qo/s2TnSUmfLz+32CvLC4RMVkzEFYjxqyti1KhByvEacEdMWBpCuSSQ+IFRT84QjGPBCuz/cBom8PfSm3GjEsGc8PkdEEOEr
  urlusa: https://developers.onemap.sg/commonapi/search?searchVal={0}&returnGeom=Y&getAddrDetails=Y&pageNum=1

login:
  form:
    url: /login/oauth2
  otp:
    get:
      url: /otp/{0}?operation=GET_NEW?duration
    verify:
      url: /otp/{0}?operation=VERIFY_CODE&code={1}

static:
  resources:
    server:
      url:  http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com

landing:
  page:
    url: http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com/AgencySales/workspace/
    
websocket:
  url: http://localhost:8089/registerWebsocketNotification

security:
  oauth2:
    enabled: true
    server: http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com
    client:
      client-id: uic-web
      client-secret: uicsecret
      access-token-uri: http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com/ife-infra-oauth2/oauth/token
      user-authorization-uri: http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com/ife-infra-oauth2/oauth/authorize
      scope:
        - user
    resource:
      user-info-uri: http://integral-reg-204-1958660911.ap-southeast-1.elb.amazonaws.com/ife-infra-oauth2/user
    token:
      refresh_token:
        url: /ife-infra-oauth2/oauth/token?grant_type=refresh_token&refresh_token=
      client_credentials:
        url: /ife-infra-oauth2/oauth/token?grant_type=client_credentials&scope=application
      revoke:
        url: /ife-infra-oauth2/oauth/{0}/revoke
    logout:
      url: /ife-infra-oauth2/customlogout?redirect_uri=
    login:
      #url: /workspace?role=
      url: /workspace
  github:
    client:
      client-id: 4b55bf091989d0db3219
      client-secret: d7d094ac9ba9420fec0313196a6892c173525942
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
  facebook:
    client:
      client-id: 233668646673605
      client-secret: 33b17e044ee6a4fa383f46ec6e28ea1d
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      user-info-uri: https://graph.facebook.com/me
    
key-management:
  server-url: http://localhost:9999
  master-key-uri: /ife-infra-oauth2/kms/masterKey
  data-key-uri: /ife-infra-oauth2/kms/dataKey

logging:
  level:
    org.springframework.security: debug

workspace:
  view:
    name: index
